name: vape_store
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  awesome_dialog: ^3.1.0
  build_runner: ^2.4.6
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  dropdown_search: ^5.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  freezed: 2.4.1
  freezed_annotation: ^2.4.1
  google_fonts: ^5.1.0
  http: ^1.1.0
  intl: ^0.18.1
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.1
  webview_flutter: ^4.2.4

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
